name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - New restaurant chain
        - New feature
        - Improvement to existing feature
        - UI/UX improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the feature or improvement you'd like to see.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why?
      placeholder: What problem does this solve or what value does it add?
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: Screenshots, links, examples, etc.
    validations:
      required: false
